ripnetstream_cpp:	main.cpp
	g++ -O3 -o ripnetstream main.cpp ../../api/lib/libfmodex64.so

ripnetstream_c:	main.c
	g++ -O3 -o ripnetstream main.c ../../api/lib/libfmodex64.so

run:
	./ripnetstream

clean:
	rm -f ripnetstream
