usercreatedsound_cpp:	main.cpp
	g++ -O3 -o usercreatedsound main.cpp ../../api/lib/libfmodex64.so

usercreatedsound_c:	main.c
	g++ -O3 -o usercreatedsound main.c ../../api/lib/libfmodex64.so

run:
	./usercreatedsound

clean:
	rm -f usercreatedsound
